### ISSUE TITLE
Error: Could not locate Bootstrapper. (File does not exist)

### ISSUE THREAD

**Issue by Janmm14** [helios-decompiler/bootstrapper#1]
Starting through the console I get this error after I closed the error window.
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException
        at com.samczsun.helios.bootstrapper.Bootstrapper.locateBootstrapperFile(Bootstrapper.java:138)
        at com.samczsun.helios.bootstrapper.Bootstrapper.<clinit>(Bootstrapper.java:95)
```
OS: Win 7
Java:
```
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

**Comment by samczsun** [comment]
That check is triggered if the supposed Bootstrapped file is either not a file, not readable, or not writable. I should remove the writable check but in the meantime could you check if those conditions are met?

**Comment by Janmm14** [comment]
The file is definitely there and I checked windows file rights, I seem to have all perms like my administrator account. I started cmd as administrator and recieved the same issue.

Is it possible that it fails due to spaces in the path to the bootstrap jar? I tested on a path without spaces and all runs fine.

**Comment by samczsun** [comment]
Ugh. Could be. I'll have to check later
